name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Update metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          committer_message: "chore: update ${filename}"
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, base.repositories, base.activity+community, isocalendar, music
          output_condition: skip-if-only-metadata-changed
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, vba, tsql, scss, gherkin, vim, vim script, handlebars, XSLT
          plugin_isocalendar: yes
